### ISSUE TITLE
Compiling ATR

### ISSUE THREAD

**Issue by solidogen** [indieboyalex/AndroidUtilities#1]
Hi Jeff,

I'm trying to compile ATR.

I found out your library cannot be found on classpath (bintray down). After a while I found this, but not every class is available. In the last commit you deleted most util.android.util classes and "moved to a new library". 

Where is this library?

Can you give me access to the new library (or at least .aar so I can compile the app)?

Thanks a lot for help!

**Comment by indieboyalex** [comment]
What version is ATR trying to use? I'll see if I can dig something out

**Comment by solidogen** [comment]
ATR is using
`implementation 'util.android:coreutilities:1.6.1'`

I managed to found your second repository and swapped for
`implementation 'util.android:library:1.6.5'`

All classes are found now, so I think this is fine :)

The only missing things I need are dexguard classes like `dexguard.util.EncryptedWebViewClient`, I downloaded dexguard.jar from some github repo but it doesn't resolve for me yet.

Anyway, that's it from library's perspective, so I'm closing :)

**Comment by indieboyalex** [comment]
Yeah DexGuard stuff will need dexguard itself.
